In [ ]:
# cd C:\Git\Hard_skills
! git add *
! git commit -m "numpy"
! git push origin main

In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
a.dot(b)

85

In [3]:
np.dot(a,b)

85

Для работы с векторами есть специальные функции перемножения
* inner это обычное скалярное умножение
* outer это внешнее умножение, то есть первый вектор будет столбец, а второй строка, тогда у нас будет матрица, в которой будет количество строк
равное количеству элементов первого вектора и количество столбцов равное количеству элементов второго вектора.

In [4]:
np.inner(a,b)

85

@ перегружен для векторов и выполняет обычное внутреннее перемножение

In [6]:
a @ b

85

In [8]:
c = np.outer(a, b)
c

array([[ 3,  4,  5,  6,  7],
       [ 6,  8, 10, 12, 14],
       [ 9, 12, 15, 18, 21],
       [12, 16, 20, 24, 28],
       [15, 20, 25, 30, 35]])

In [9]:
c @ c

array([[ 255,  340,  425,  510,  595],
       [ 510,  680,  850, 1020, 1190],
       [ 765, 1020, 1275, 1530, 1785],
       [1020, 1360, 1700, 2040, 2380],
       [1275, 1700, 2125, 2550, 2975]])

Ранк матрицы - это количество линейно независимых строк и столбоц, то есть максимальный размер матрицы с ненулевым детерминантом
Если ранк матрицы n, то она может описывать систему из n линейно независимых уравнений

In [10]:
np.linalg.matrix_rank(c)

1

In [17]:
np.linalg.det(c)

0.0

In [15]:
ar = np.random.randint(1,9, size=(3, 3))
ar

array([[5, 3, 3],
       [3, 4, 6],
       [5, 8, 4]])

In [16]:
np.linalg.matrix_rank(ar)

3

Решение системы лин уравнений

In [19]:
a = ar
y = np.array([3,2,1])
x = np.linalg.solve(a, y)
x

array([ 0.70212766, -0.45744681,  0.28723404])

In [20]:
inv_a = np.linalg.inv(a)
inv_a

array([[ 0.34042553, -0.12765957, -0.06382979],
       [-0.19148936, -0.05319149,  0.22340426],
       [-0.04255319,  0.26595745, -0.11702128]])

In [23]:
x = inv_a.dot(y)
x

array([ 0.70212766, -0.45744681,  0.28723404])

In [24]:
a @ inv_a

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [25]:
np.linalg.det(a)

-94.0

In [26]:
np.linalg.eig(a)

(array([13.66745043,  2.30995156, -2.97740199]),
 array([[ 0.43783001,  0.83811759, -0.04822903],
        [ 0.56826283, -0.46283608, -0.63924327],
        [ 0.69669379, -0.28868956,  0.76749072]]))

In [4]:
a = np.array([1,1,2,2,4,2,3,3,3])
np.unique(a, return_counts=True)

(array([1, 2, 3, 4]), array([2, 3, 3, 1], dtype=int64))

In [14]:
ar_set, indx = np.unique(a, return_inverse=True)
np.unique(a, return_inverse=True)

(array([1, 2, 3, 4]), array([0, 0, 1, 1, 3, 1, 2, 2, 2], dtype=int64))

In [15]:
ar_set[indx]

array([1, 1, 2, 2, 4, 2, 3, 3, 3])

In [22]:
a = np.array([1,2,1,1,1,2,1,1,1])
a.resize(3,4)
a

array([[1, 2, 1, 1],
       [1, 2, 1, 1],
       [1, 0, 0, 0]])

In [23]:
np.unique(a)

array([0, 1, 2])

In [24]:
np.unique(a, axis=0)

array([[1, 0, 0, 0],
       [1, 2, 1, 1]])

In [29]:
import pandas as pd
ser = pd.Series([2,1,3,5,7])
ser2 = pd.Series([1,2,3,4])
np.in1d(ser, ser2)

array([ True,  True,  True, False, False])

In [30]:
np.intersect1d(ser, ser2)

array([1, 2, 3], dtype=int64)

In [31]:
np.union1d(ser, ser2)

array([1, 2, 3, 4, 5, 7], dtype=int64)

In [32]:
columns = np.array(['name', 'gender', 'department', 'salary'])

In [33]:
np.setdiff1d(columns, ['gender'])

array(['department', 'name', 'salary'], dtype='<U10')

: 

In [1]:
import numpy as np

In [5]:
a = np.arange(6).reshape(2,1,3)
b = np.arange(12).reshape(4,3)

In [6]:
a

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [7]:
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
a + b

array([[[ 0,  2,  4],
        [ 3,  5,  7],
        [ 6,  8, 10],
        [ 9, 11, 13]],

       [[ 3,  5,  7],
        [ 6,  8, 10],
        [ 9, 11, 13],
        [12, 14, 16]]])

Чтобы транслировать массивы разной длинны их можно привести к одной размерности добавляя у каждого новую ось 
Мы можем добавить новую ось в любое место при условии, что она содержит 1 элемент
По сути мы просто вставляем измерение и следующие за этой осью измерения как бы сдвигаются
Нпример была у нас табличка 2 оси
Если мы добавим третью ось в начало, то у нас наши оси сдвинуться и будут 2 и 3 ей осью, а были 1 и 2
То есть мы получим кубик с одной строкой, так как мы добавили одну новую ось и 2 столбца и в каждой ячейке будет список по третьему измерению из 3 элементов

In [20]:
a = np.array([1,2,3])
b = np.array([3,5])
c = np.array([1,2,3,6])
a.shape = 1, 1, -1
b.shape = 1, -1, 1
c.shape = -1, 1, 1


In [21]:
a

array([[[1, 2, 3]]])

In [22]:
b

array([[[3],
        [5]]])

In [23]:
c

array([[[1]],

       [[2]],

       [[3]],

       [[6]]])

In [24]:
a + b * c

array([[[ 4,  5,  6],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [11, 12, 13]],

       [[10, 11, 12],
        [16, 17, 18]],

       [[19, 20, 21],
        [31, 32, 33]]])

Можно добавлять оси не руками указывая 1 в shape
А использовать функцию

In [28]:
a = np.array([1,2,3])
b = np.array([3,5])
c = np.array([1,2,3,6])
an, bn, cn = np.ix_(a, b, c)
print(an.shape)
print(bn.shape)
print(cn.shape)

(3, 1, 1)
(1, 2, 1)
(1, 1, 4)


In [33]:
a = np.array([1,2,3])
b = np.array([3,5])
an, bn = np.ix_(a,b)
print(an.shape)
print(bn.shape)
an * bn

(3, 1)
(1, 2)


array([[ 3,  5],
       [ 6, 10],
       [ 9, 15]])

In [15]:
info = np.array([
    ('Sam', 1990, 170.2)
    ,('Tony', 1995, 170.5)
    ,('Arnold', 1997, 188.6)]
    , dtype= [
        ('Name', 'U10')
        , ('Age', 'int')    
        , ('Height', 'float')
    ])
info

array([('Sam', 1990, 170.2), ('Tony', 1995, 170.5),
       ('Arnold', 1997, 188.6)],
      dtype=[('Name', '<U10'), ('Age', '<i4'), ('Height', '<f8')])

In [16]:
info['Name']

array(['Sam', 'Tony', 'Arnold'], dtype='<U10')

In [17]:
info['Height']

array([170.2, 170.5, 188.6])

In [18]:
info[['Name', 'Age']]

array([('Sam', 1990), ('Tony', 1995), ('Arnold', 1997)],
      dtype={'names':['Name','Age'], 'formats':['<U10','<i4'], 'offsets':[0,40], 'itemsize':52})

In [22]:
info[0][2]

170.2

In [23]:
info['Age'][1]

1995

In [24]:
np.save('info.npy', info)

In [25]:
new = np.load('info.npy')
new

array([('Sam', 1990, 170.2), ('Tony', 1995, 170.5),
       ('Arnold', 1997, 188.6)],
      dtype=[('Name', '<U10'), ('Age', '<i4'), ('Height', '<f8')])

In [41]:
ages = np.array([[22, 42, 27, 34], [21, 22, 34, 54]])
ages

array([[22, 42, 27, 34],
       [21, 22, 34, 54]])

In [39]:
np.savetxt('numpy_ages.csv', ages, delimiter=',')

In [2]:
a = np.array([1,2,3, 0, np.inf])
vfunc = np.vectorize(lambda x: x if x != 0 else np.inf)
vfunc(a)

array([ 1.,  2.,  3., inf, inf])