In [11]:
! git add *
! git commit -m "numpy"
! git push origin main

C:\Git\Hard_skills


In [12]:
cd C:\Git\Hard_skills
# ! git add *
# ! git commit -m "numpy"
# ! git push origin main

SyntaxError: invalid syntax (4245486734.py, line 1)

In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 4, 5, 6, 7])
a.dot(b)

85

In [3]:
np.dot(a,b)

85

Для работы с векторами есть специальные функции перемножения
* inner это обычное скалярное умножение
* outer это внешнее умножение, то есть первый вектор будет столбец, а второй строка, тогда у нас будет матрица, в которой будет количество строк
равное количеству элементов первого вектора и количество столбцов равное количеству элементов второго вектора.

In [4]:
np.inner(a,b)

85

@ перегружен для векторов и выполняет обычное внутреннее перемножение

In [6]:
a @ b

85

In [8]:
c = np.outer(a, b)
c

array([[ 3,  4,  5,  6,  7],
       [ 6,  8, 10, 12, 14],
       [ 9, 12, 15, 18, 21],
       [12, 16, 20, 24, 28],
       [15, 20, 25, 30, 35]])

In [9]:
c @ c

array([[ 255,  340,  425,  510,  595],
       [ 510,  680,  850, 1020, 1190],
       [ 765, 1020, 1275, 1530, 1785],
       [1020, 1360, 1700, 2040, 2380],
       [1275, 1700, 2125, 2550, 2975]])

Ранк матрицы - это количество линейно независимых строк и столбоц, то есть максимальный размер матрицы с ненулевым детерминантом
Если ранк матрицы n, то она может описывать систему из n линейно независимых уравнений

In [10]:
np.linalg.matrix_rank(c)

1

In [17]:
np.linalg.det(c)

0.0

In [15]:
ar = np.random.randint(1,9, size=(3, 3))
ar

array([[5, 3, 3],
       [3, 4, 6],
       [5, 8, 4]])

In [16]:
np.linalg.matrix_rank(ar)

3

Решение системы лин уравнений

In [19]:
a = ar
y = np.array([3,2,1])
x = np.linalg.solve(a, y)
x

array([ 0.70212766, -0.45744681,  0.28723404])

In [20]:
inv_a = np.linalg.inv(a)
inv_a

array([[ 0.34042553, -0.12765957, -0.06382979],
       [-0.19148936, -0.05319149,  0.22340426],
       [-0.04255319,  0.26595745, -0.11702128]])

In [23]:
x = inv_a.dot(y)
x

array([ 0.70212766, -0.45744681,  0.28723404])

In [24]:
a @ inv_a

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [-5.55111512e-17,  1.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])

In [25]:
np.linalg.det(a)

-94.0

In [26]:
np.linalg.eig(a)

(array([13.66745043,  2.30995156, -2.97740199]),
 array([[ 0.43783001,  0.83811759, -0.04822903],
        [ 0.56826283, -0.46283608, -0.63924327],
        [ 0.69669379, -0.28868956,  0.76749072]]))